#!/usr/bin/env python3

import torch

BIN_MOD = 2

RING_BITLENGTH = 32
RING_MIN = -2 ** (RING_BITLENGTH - 1)
RING_MAX = 2 ** (RING_BITLENGTH - 1) - 1

SFN_FRACTION = 14
SFN_FACTOR = 2 ** SFN_FRACTION

EXT_RING_BITLENGTH = RING_BITLENGTH + SFN_FRACTION
EXT_RING_MIN = -2 ** (EXT_RING_BITLENGTH - 1)
EXT_RING_MAX = 2 ** (EXT_RING_BITLENGTH - 1) - 1
EXT_RING_MOD = 2 ** EXT_RING_BITLENGTH

BOOL_TYPE = torch.bool
SFN_TYPE = torch.int32
EXT_SFN_TYPE = torch.int64
